### PR TITLE
Fix REPL and Emotes

### PR DESCRIPTION
**Pull request by Martmists-GH**
(pls dont merge until I fixed emotes thx)

### CODE REVIEW

**Comment by Ratismal** [comment]
Is this ready?

**Comment by Ratismal** [comment]
@martmists is this ready for merging?

**Comment by Martmists-GH** [comment]
Not yet, I found a snippet to make stuff draggable similarly to $(...).draggable, but it may take some time to implement. Expect it to be done around Wednesday next week-ish

**Comment by Martmists-GH** [comment]
The above commit might be interesting to put into DiscordInjections natively to make a window draggable. It requires the element to be made draggable to be a child of the `body` element, and handles all dragging.

**Comment by Snazzah** [comment]
Is it finished?

**Comment by Martmists-GH** [comment]
Feel free to merge for now, I'm leaving Emotes open for fixing as it need to have lag reduced as well

**Pull request merged**
